apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: production
data:
  DATABASE_HOST: "postgres-service"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "docker run -d \
  --name sonarqube \
  -p 9000:9000 \
  -e SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true \
  sonarqube:community"
  FRONTEND_URL: "https://your-domain.com"
  NODE_ENV: "production"
