apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-uploads-pvc
  namespace: production
spec:
  accessModes:
    - ReadWriteOnce       # Minikube ne supporte pas ReadWriteMany sans addon NFS
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard   # storageClass par défaut de Minikube