apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: production
type: Opaque
stringData:
  DB_USERNAME: "postgres"
  DB_PASSWORD: "postgres"
  JWT_ACCESS_SECRET: "3a035305bb7a7bb7bc230fe83557d4cd5ab0c739698a0ccc44db38f598e288ff"
  JWT_REFRESH_SECRET: "9f6c2e8a4b7d1f3a5c0e9b8d4a2f7c1e6b5d0a3f8e1c9b7a2d6e4f0b1c5a8"
  GMAIL_USER: "novaentra2026@gmail.com"
  GMAIL_PASS: "enrqztjhkqbryrar"
  GEMINI_API_KEY: "your-gemini-api-key"